### ISSUE TITLE
JeKyll 3 support

### ISSUE THREAD

**Issue by baires** [gjtorikian/jekyll-conrefifier#10]
Any update on supporting Jekyll 3? I see that there is a specific branch for that.

I would love to use this gem

Cheers!

**Comment by gjtorikian** [comment]
A problem I found was that I was trying to decide between supporting Jekyll 2 and, or just 3. I couldn't settle on one or the other at the time.

**Comment by baires** [comment]
I understand. If you ask me I will always go bet on the last release.

**Comment by heitorPB** [comment]
Any updates on this?

**Comment by DirtyF** [comment]
Tests currently fail on latest Jekyll 3.x:

```
An error occurred while loading ./spec/conrefifier_spec.rb.
Failure/Error: alias_method :old_read_collections, :read_collections

NameError:
  undefined method `read_collections' for class `Jekyll::Site'
```

This method has been extracted to reader in https://github.com/jekyll/jekyll/commit/2f88a0c0a172504a6a03809239a6343153134737

/cc @jekyll/plugin-core if someone want to take a stab at this

**Comment by liquidvisual** [comment]
Jekyll is becoming harder and harder to justify working with. Maybe it's time for Hugo or something else?

**Comment by baires** [comment]
I give up on jekyll two years ago.

**Comment by gjtorikian** [comment]
> Jekyll is becoming harder and harder to justify working with.

> I give up on jekyll two years ago.

Same, to be honest. I use nanoc for Ruby and Hugo for Go these days. Jekyll is nice for super simple stuff.
